FROM caddy:builder AS builder

WORKDIR /src

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    xcaddy build \
    --output /usr/bin/caddy \
    --with github.com/shyndman/caddy-oidc=.

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY e2e/Caddyfile /etc/caddy/Caddyfile

